version: '3.4'

services:
    proxy:
      build: ./apps/proxy
      networks:
          webservices:
      # volumes:
      #   - ./apps/proxy/sites-enabled/proxies.conf:/etc/nginx/conf.d/proxies.conf
      #   - ./apps/proxy/html:/usr/share/nginx/html
      ports:
        - 8088:8080

    worder-1:
        build: ./apps/app-1
        # ports:
        #   - 444:80
        # volumes:
        #   - ./apps/app-1/src:/var/www/html
        #   - ./apps/app-1/config.json:/var/www/config.json
        networks:
            webservices:
              aliases:
                - ct-app-1

    worder-2:
        build: ./apps/app-2
        networks:
            webservices:
              aliases:
                - ct-app-2

networks:
  webservices:
